# Generated by Django 2.2 on 2019-04-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190420_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveduc1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveduc2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveduc3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveducdate1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveducdate2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveducdate3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveducdesc1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveducdesc2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveducdesc3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveducuniv1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveducuniv2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preveducuniv3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prevjob1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prevjob2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prevjobcorp1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prevjobcorp2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prevjobdate1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prevjobdate2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prevjobdesc1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prevjobdesc2',
        ),
    ]
