# Generated by Django 2.2 on 2019-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190420_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='no_telp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
