# Generated by Django 2.2 on 2019-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190420_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preveducdate1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preveducdate2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preveducdate3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prevjobdate1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prevjobdate2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
